blogger/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get '/articles', controller: 'articles', action: 'index'
  resources :articles
  root to: "articles#index"
  get '/articles', to: 'articles#index'
  get '/articles/:id(.:format)', to: 'articles#show'
  get 'articles/new', to: 'articles#new'
  post '/articles/new', to: 'articles#create'
  get '/articles/:id/edit', to: 'articles#edit'
  put '/articles/:id', to: 'articles#update'
  delete '/articles/:id', to: 'articles#destory'
end

blogger/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blogger/app/models/article.rb
class Article < ApplicationRecord
      validates :title, presence: true,
                        length: { minimum: 5 }
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params_validate)
 
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def destroy
        @article = Article.find (params[:id])
        @article.destroy
        redirect_to @article

    end

    private
    def article_params_validate
        params.require(:article).permit(:title, :body)
    end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
end

blogger/app/views/articles/create.html.erb
<p>testing this render</p>
<%= render plain: params[:article].inspect %>

blogger/app/views/articles/index.html.erb
<h1>welcome to my rails app</h1>
<p>by rootDEV2990</p>
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<h3>Aricles</h3>
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

blogger/app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@article.errors.count, "error") %>
            found, please correct them and try again:
        </h2>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
</p>

<p>
    <%= f.submit %>
</p>
<% end %>

<%= link_to 'Back', articles_path %>

blogger/app/views/articles/show.html.erb
<h1>Show view page</h1>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.body %>
</p>
<%= link_to "Delete", article_path(@article), method: :delete %>
<%= link_to 'Back', articles_path %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>